/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Ctr_factura;
import Controlador.Ctr_productos;
import Controlador.Ctr_ventas;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class D_Nueva_Ventas extends javax.swing.JDialog {

    /**
     * Creates new form D_ventas
     */
    private int controlador_de_rows = 0;
    private float sub_total, IVA, Total;
    private int stock_de_producto_a_vender=0;//esta variable controla que dentro de la misma venta no se facturen mas productos que los que en ese momento hay disponible
    //creamos un objeto para dar formato a los decimales
    DecimalFormat df = new DecimalFormat("#.00");

    //declaramos un arreglo donde guardaremos el detalle de los productos vendidos , es decir lo que está en el jtable
    public D_Nueva_Ventas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/IVED_isotipo.png")).getImage());
        //adaptamos el tamaño del formulario a la pantalla de tal forma que salga maximizado siempre
        //this.setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds());
        this.setLocationRelativeTo(null);
        this.txt_sub_total.setText(String.valueOf(sub_total));
        this.txt_iva.setText(String.valueOf(IVA));
        this.txt_total.setText(String.valueOf(Total));

        this.setTitle("IVED-Ventas");

        //personalizar tabla de los productos a vender
        this.Table_productos_ventas.getTableHeader().setBackground(new Color(36, 36, 36));
        this.Table_productos_ventas.getTableHeader().setForeground(Color.WHITE);
        this.Table_productos_ventas.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 12));
        
        //establecemos la fecha actual para el jdatchooser
        ObtenerFechaActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel_producto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_codigo_buscar = new javax.swing.JTextField();
        btn_buscar = new rsbuttom.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        spin_cantidad_a_vender = new javax.swing.JSpinner();
        btn_agregar_al_carrito = new rsbuttom.RSButtonMetro();
        btn_limpiar = new rsbuttom.RSButtonMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_productos_ventas = new javax.swing.JTable();
        btn_buscar3 = new rsbuttom.RSButtonMetro();
        btn_buscar4 = new rsbuttom.RSButtonMetro();
        jLabel9 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_id_factura = new javax.swing.JTextField();
        txt_sub_total = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        Jdate_fecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Panel_producto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Codigo:");

        txt_codigo_buscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_codigo_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_codigo_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigo_buscarActionPerformed(evt);
            }
        });
        txt_codigo_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigo_buscarKeyPressed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(51, 102, 255));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btn_buscar.setColorHover(new java.awt.Color(0, 0, 0));
        btn_buscar.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_buscar.setFocusable(false);
        btn_buscar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txt_nombre.setEditable(false);
        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Marca:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txt_marca.setEditable(false);
        txt_marca.setBackground(new java.awt.Color(255, 255, 255));
        txt_marca.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 260, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Descripción:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Stock:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        txt_cantidad.setEditable(false);
        txt_cantidad.setBackground(new java.awt.Color(255, 255, 255));
        txt_cantidad.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_cantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 123, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("Codigo:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_ID.setEditable(false);
        txt_ID.setBackground(new java.awt.Color(255, 255, 255));
        txt_ID.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });
        jPanel3.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 400, -1));

        txt_descripcion.setEditable(false);
        txt_descripcion.setBackground(new java.awt.Color(255, 255, 255));
        txt_descripcion.setColumns(20);
        txt_descripcion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_descripcion.setRows(5);
        txt_descripcion.setAutoscrolls(false);
        txt_descripcion.setBorder(null);
        txt_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_descripcionKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txt_descripcion);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 620, 100));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Precio Unitario:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        txt_precio.setEditable(false);
        txt_precio.setBackground(new java.awt.Color(255, 255, 255));
        txt_precio.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_precio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 123, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setText("Cantidad a vender");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        spin_cantidad_a_vender.setFont(new java.awt.Font("Century Gothic", 1, 72)); // NOI18N
        jPanel3.add(spin_cantidad_a_vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 200, 100));

        btn_agregar_al_carrito.setBackground(new java.awt.Color(51, 102, 255));
        btn_agregar_al_carrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito-de-compras.png"))); // NOI18N
        btn_agregar_al_carrito.setText("Agregar a la venta");
        btn_agregar_al_carrito.setColorHover(new java.awt.Color(0, 0, 0));
        btn_agregar_al_carrito.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_agregar_al_carrito.setFocusable(false);
        btn_agregar_al_carrito.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_agregar_al_carrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_al_carritoActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(79, 184, 80));
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png"))); // NOI18N
        btn_limpiar.setText("Limpiar Campos");
        btn_limpiar.setColorHover(new java.awt.Color(0, 0, 0));
        btn_limpiar.setColorNormal(new java.awt.Color(79, 184, 80));
        btn_limpiar.setFocusable(false);
        btn_limpiar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        Table_productos_ventas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Table_productos_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Sub Total"
            }
        ));
        Table_productos_ventas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Table_productos_ventas.setEnabled(false);
        Table_productos_ventas.setFocusable(false);
        Table_productos_ventas.setSelectionBackground(new java.awt.Color(51, 102, 255));
        Table_productos_ventas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Table_productos_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_productos_ventasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table_productos_ventas);
        if (Table_productos_ventas.getColumnModel().getColumnCount() > 0) {
            Table_productos_ventas.getColumnModel().getColumn(0).setPreferredWidth(100);
            Table_productos_ventas.getColumnModel().getColumn(1).setPreferredWidth(350);
            Table_productos_ventas.getColumnModel().getColumn(2).setPreferredWidth(100);
            Table_productos_ventas.getColumnModel().getColumn(3).setPreferredWidth(100);
            Table_productos_ventas.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        javax.swing.GroupLayout Panel_productoLayout = new javax.swing.GroupLayout(Panel_producto);
        Panel_producto.setLayout(Panel_productoLayout);
        Panel_productoLayout.setHorizontalGroup(
            Panel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_productoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_codigo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_productoLayout.createSequentialGroup()
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_agregar_al_carrito, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE))
        );
        Panel_productoLayout.setVerticalGroup(
            Panel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_productoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_codigo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar_al_carrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btn_buscar3.setBackground(new java.awt.Color(51, 102, 255));
        btn_buscar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Listo.png"))); // NOI18N
        btn_buscar3.setText("Realizar Venta");
        btn_buscar3.setColorHover(new java.awt.Color(0, 0, 0));
        btn_buscar3.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_buscar3.setFocusable(false);
        btn_buscar3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_buscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar3ActionPerformed(evt);
            }
        });

        btn_buscar4.setBackground(new java.awt.Color(255, 27, 45));
        btn_buscar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito-de-compras.png"))); // NOI18N
        btn_buscar4.setText("Limpiar Venta");
        btn_buscar4.setColorHover(new java.awt.Color(0, 0, 0));
        btn_buscar4.setColorNormal(new java.awt.Color(255, 27, 45));
        btn_buscar4.setFocusable(false);
        btn_buscar4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_buscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar4ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("Cliente:");

        txt_cliente.setBackground(new java.awt.Color(204, 204, 204));
        txt_cliente.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clienteActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("Fecha:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setText("Factura N°:");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setText("Sub total:");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("IVA:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("Total:");

        txt_id_factura.setBackground(new java.awt.Color(204, 204, 204));
        txt_id_factura.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_id_factura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_id_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_facturaActionPerformed(evt);
            }
        });
        txt_id_factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_id_facturaKeyPressed(evt);
            }
        });

        txt_sub_total.setEditable(false);
        txt_sub_total.setBackground(new java.awt.Color(204, 204, 204));
        txt_sub_total.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_sub_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_sub_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sub_totalActionPerformed(evt);
            }
        });

        txt_iva.setEditable(false);
        txt_iva.setBackground(new java.awt.Color(204, 204, 204));
        txt_iva.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_iva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ivaActionPerformed(evt);
            }
        });

        txt_total.setEditable(false);
        txt_total.setBackground(new java.awt.Color(204, 204, 204));
        txt_total.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_buscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_buscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_id_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel10)
                            .addGap(332, 332, 332)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Jdate_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Panel_producto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Panel_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txt_id_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(Jdate_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txt_sub_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_buscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ivaActionPerformed

    private void txt_sub_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sub_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sub_totalActionPerformed

    private void txt_id_facturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_facturaKeyPressed
        // TODO add your handling code here:
        //validamos que solo se admitan numeros como codigo de factura
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            //si es un numero, todo bien
        }else{
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo debe escribir numeros","¡Error!",JOptionPane.ERROR_MESSAGE);
            this.txt_id_factura.setText("");
        }
    }//GEN-LAST:event_txt_id_facturaKeyPressed

    private void txt_id_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_facturaActionPerformed

    private void txt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clienteActionPerformed

    private void btn_buscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar4ActionPerformed
        // TODO add your handling code here:
        //al limpiar o cancelar la venta , las unidades antes facturadas deben de regresar al inventario
        int unidades_facturadas=0;
        for(int i=0;i<this.controlador_de_rows;i++){
            Ctr_productos ctr=new Ctr_productos();

            unidades_facturadas=Integer.parseInt(this.Table_productos_ventas.getValueAt(i,2).toString());
            int nuevas_unidades=ctr.obtenterStock(this.Table_productos_ventas.getValueAt(i,0).toString())+unidades_facturadas;

            //actualizamos las unidades
            ctr.actualizar_cantidad_unidades(nuevas_unidades,this.Table_productos_ventas.getValueAt(i,0).toString());
        }
        //en este boton se va a limpiar la venta en su totalidad
        limpiar_toda_venta();
        this.controlador_de_rows=0;
    }//GEN-LAST:event_btn_buscar4ActionPerformed

    private void btn_buscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar3ActionPerformed
        // TODO add your handling code here:
        //validamos que todos los parametros de l a venta sean los correctos

        if (this.txt_cliente.getText().isEmpty() || this.txt_id_factura.getText().isEmpty() || this.Jdate_fecha.getDate().toString() == "" ||this.controlador_de_rows==0) {
            JOptionPane.showMessageDialog(this, "No se pudo completar la venta", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String[][] Detalle_tabla_productos = new String[this.controlador_de_rows][5];
            //llenamos el arreglo con el contenido de la table
            for (int filas = 0; filas < this.controlador_de_rows; filas++) {
                //recorremos las columnas
                for (int columnas = 0; columnas < 5; columnas++) {
                    Detalle_tabla_productos[filas][columnas] = this.Table_productos_ventas.getValueAt(filas, columnas).toString();
                }
            }
            SimpleDateFormat formato=new SimpleDateFormat("dd-MM-yyyy");
            String fecha=formato.format(this.Jdate_fecha.getDate());
            D_venta_realizada dv = new D_venta_realizada(new javax.swing.JFrame(), true, this.txt_cliente.getText(), fecha,
                this.txt_id_factura.getText(), Float.parseFloat(this.txt_sub_total.getText()),
                Float.parseFloat(this.txt_iva.getText()), Float.parseFloat(this.txt_total.getText()),
                Detalle_tabla_productos, this.controlador_de_rows);
            //registramos la factura
            Ctr_factura cf=new Ctr_factura();
            cf.Registrar_factura(this.txt_id_factura.getText().trim(), fecha,this.txt_cliente.getText().trim(), sub_total, IVA, Total,"Activa");
            //registramos la venta de los productos
            Ctr_ventas cv=new Ctr_ventas();
            for(int i=0;i<this.controlador_de_rows;i++){
                String codigo_identificador=this.Table_productos_ventas.getValueAt(i,0).toString();
                int Cantidad_vendida=Integer.parseInt(this.Table_productos_ventas.getValueAt(i,2).toString());
                float Precio_unitario=Float.parseFloat(this.Table_productos_ventas.getValueAt(i,3).toString());
                String Codigo_factura=this.txt_id_factura.getText().trim();
                cv.agregar_venta(codigo_identificador, Cantidad_vendida, Precio_unitario, Codigo_factura);
            }
            dv.setVisible(true);
            while(dv.isShowing()){
                //no hace nada
            }
            limpiar_toda_venta();
        }

    }//GEN-LAST:event_btn_buscar3ActionPerformed

    private void Table_productos_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_productos_ventasMouseClicked
        // TODO add your handling code here:
        //al hacer doble click en el detalle se podrá eliminar o editar
        if (evt.getClickCount() == 2) {

            int select = this.Table_productos_ventas.rowAtPoint(evt.getPoint());

            String codigo_producto = this.Table_productos_ventas.getValueAt(select, 0).toString();
            int opc = JOptionPane.showConfirmDialog(null, "Desea retirar de la factura el producto de Codigo " + codigo_producto + "?");

            if (opc == 0) {
                //detenemos la aplicacion---------------
                int cantidades_regresan_inventario = Integer.parseInt(this.Table_productos_ventas.getValueAt(select, 2).toString());
                Ctr_productos ctr = new Ctr_productos();
                int stock_disponible_al_momento = ctr.obtenterStock(codigo_producto);
                ctr.actualizar_cantidad_unidades((stock_disponible_al_momento + cantidades_regresan_inventario), codigo_producto);
                DefaultTableModel modelPrincipal = (DefaultTableModel) this.Table_productos_ventas.getModel();

                float sub_total_eliminado = Float.parseFloat(this.Table_productos_ventas.getValueAt(select, 3).toString());
                //restamos el subtotal eliminado y lo volvemos a calcular
                this.sub_total = sub_total - sub_total_eliminado;
                this.IVA = (float) (sub_total * 0.15);
                this.Total = sub_total + IVA;
                df.format(IVA);
                this.txt_sub_total.setText(String.valueOf(sub_total));
                this.txt_iva.setText(String.valueOf(IVA));
                this.txt_total.setText(String.valueOf(Total));

                this.Table_productos_ventas.setModel(modelPrincipal);
                //mostramos las nuevas unidades disponibles
                stock_disponible_al_momento = ctr.obtenterStock(codigo_producto);
                this.txt_cantidad.setText(String.valueOf(stock_disponible_al_momento));
                controlador_de_rows--;
                modelPrincipal.removeRow(select);

            } else {

            }

        }
    }//GEN-LAST:event_Table_productos_ventasMouseClicked

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar_campos();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_agregar_al_carritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_al_carritoActionPerformed
        // TODO add your handling code here:

        this.stock_de_producto_a_vender = Integer.parseInt(this.txt_cantidad.getText()) - Integer.parseInt(this.spin_cantidad_a_vender.getValue().toString());
        //validamos que la venta sea correcta
        if (Integer.parseInt(this.spin_cantidad_a_vender.getValue().toString()) == 0 || this.txt_codigo_buscar.getText() == "" || this.stock_de_producto_a_vender > Integer.parseInt(this.txt_cantidad.getText()) || this.stock_de_producto_a_vender < 0) {
            JOptionPane.showMessageDialog(this, "No se pudo completar la venta", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            this.txt_cantidad.setText(String.valueOf(this.stock_de_producto_a_vender));//pasamos la nueva cantida de stock
            //toca acutalizar las unidades en cuanto se agregan a la venta
            Ctr_productos ctr = new Ctr_productos();
            ctr.actualizar_cantidad_unidades(this.stock_de_producto_a_vender, this.txt_ID.getText());
            DefaultTableModel modelPrincipal = (DefaultTableModel) this.Table_productos_ventas.getModel();
            modelPrincipal.addRow(new Object[]{"", "", ""});
            this.Table_productos_ventas.setValueAt(this.txt_ID.getText().trim(), controlador_de_rows, 0);
            this.Table_productos_ventas.setValueAt(this.txt_nombre.getText(), controlador_de_rows, 1);
            this.Table_productos_ventas.setValueAt(this.spin_cantidad_a_vender.getValue().toString(), controlador_de_rows, 2);
            this.Table_productos_ventas.setValueAt(this.txt_precio.getText().trim(), controlador_de_rows, 3);
            this.Table_productos_ventas.setValueAt((Double.parseDouble(this.txt_precio.getText()) * Double.parseDouble(this.spin_cantidad_a_vender.getValue().toString())), controlador_de_rows, 4);

            controlador_de_rows++;

            //recorremos toda la columna de subtotales
            this.sub_total = 0;
            for (int i = 0; i < controlador_de_rows; i++) {
                this.sub_total += Float.parseFloat(this.Table_productos_ventas.getValueAt(i, 4).toString());
            }
            this.IVA = (float) (sub_total * 0.15);
            this.Total = sub_total + IVA;
            df.format(IVA);
            this.txt_sub_total.setText(String.valueOf(sub_total));
            this.txt_iva.setText(String.valueOf(IVA));
            this.txt_total.setText(String.valueOf(Total));

        }
    }//GEN-LAST:event_btn_agregar_al_carritoActionPerformed

    private void txt_descripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionKeyPressed
        // TODO add your handling code here:
        //limitamos la cantidad de caracteres en la descripcion 450
        if (this.txt_descripcion.getText().length() >= 450) {
            JOptionPane.showMessageDialog(this, "Haz alcanzado el limite de caracteres!", "Error", JOptionPane.ERROR_MESSAGE);
            String texto = this.txt_descripcion.getText().substring(0, 450);
            this.txt_descripcion.setText(texto);
        }
    }//GEN-LAST:event_txt_descripcionKeyPressed

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Ctr_productos ctr = new Ctr_productos();
        ctr.buscar_por_codigo_con_precio(txt_codigo_buscar.getText().trim(), txt_ID, txt_nombre, txt_marca, txt_descripcion, txt_cantidad, txt_precio);
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMaximum(Integer.parseInt(this.txt_cantidad.getText().trim()));
        nm.setMinimum(0);

        this.spin_cantidad_a_vender.setModel(nm);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_codigo_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigo_buscarKeyPressed
        // TODO add your handling code here:
        //al presionar enter accedemos a las opciones de busqyeda de la capa controlador
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (this.txt_codigo_buscar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debes de insertar un código de busqueda");
            } else {
                //hacemos la busqyeda de los datos
                Ctr_productos ctr = new Ctr_productos();
                ctr.buscar_por_codigo_con_precio(txt_codigo_buscar.getText().trim(), txt_ID, txt_nombre, txt_marca, txt_descripcion, txt_cantidad, txt_precio);
                SpinnerNumberModel nm = new SpinnerNumberModel();
                nm.setMaximum(Integer.parseInt(this.txt_cantidad.getText().trim()));
                nm.setMinimum(0);

                this.spin_cantidad_a_vender.setModel(nm);

            }
        }
    }//GEN-LAST:event_txt_codigo_buscarKeyPressed

    private void txt_codigo_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigo_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limpiar_campos() {
        this.txt_ID.setText("");
        this.txt_cantidad.setText("");
        this.txt_codigo_buscar.setText("");
        this.txt_descripcion.setText("");
        this.txt_marca.setText("");
        this.txt_nombre.setText("");
        this.txt_precio.setText("");
        this.spin_cantidad_a_vender.setValue(0);
        ObtenerFechaActual();
    }
    private void ObtenerFechaActual(){
        DateTimeFormatter dtf4 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String date=dtf4.format(LocalDateTime.now());
        try {
            Date Date = new SimpleDateFormat("dd/MM/yyyy").parse(date);
            this.Jdate_fecha.setDate(Date);
        } catch (ParseException ex) {
            Logger.getLogger(D_Nueva_Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void limpiar_toda_venta(){
        //este metodo limpiara todos los campos de la factura
        limpiar_campos();
        DefaultTableModel modelPrincipal = (DefaultTableModel) this.Table_productos_ventas.getModel();
        //eliminamos las filasd de la tabla con el detalle de los productos
        for(int i=0;i<this.controlador_de_rows;i++){
           modelPrincipal.removeRow(0);
        }
        this.Table_productos_ventas.setModel(modelPrincipal);
        this.txt_sub_total.setText("0.0");
        this.txt_iva.setText("0.0");
        this.txt_total.setText("0.0");
        this.txt_cliente.setText("");
        this.txt_id_factura.setText("");
        this.controlador_de_rows=0;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_Nueva_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_Nueva_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_Nueva_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_Nueva_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_Nueva_Ventas dialog = new D_Nueva_Ventas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Jdate_fecha;
    private javax.swing.JPanel Panel_producto;
    private javax.swing.JTable Table_productos_ventas;
    private rsbuttom.RSButtonMetro btn_agregar_al_carrito;
    private rsbuttom.RSButtonMetro btn_buscar;
    private rsbuttom.RSButtonMetro btn_buscar3;
    private rsbuttom.RSButtonMetro btn_buscar4;
    private rsbuttom.RSButtonMetro btn_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner spin_cantidad_a_vender;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_codigo_buscar;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_id_factura;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_sub_total;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

}
