/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.image.ImageObserver;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class D_venta_realizada extends javax.swing.JDialog {

    /**
     * Creates new form D_venta_realizada
     */
    //declaramos los campos que vamos a utilizar en la factura
    private String cliente,fecha,codigo_factura;
    private float sub_total,iva,total;
    private int cantidad_items;
    public D_venta_realizada(java.awt.Frame parent, boolean modal,String cliente,String fecha,String codigo_factura,float sub_total,float iva,float total,
                              String [][] Detalle_tabla_productos,int cantidad_items) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("IVED-Venta Relizada");
        this.setIconImage(new ImageIcon(getClass().getResource("/img/IVED_isotipo.png")).getImage());
        //hacemos locales los parametros que recibimos del frame anterios
        this.cliente=cliente;
        this.fecha=fecha;
        this.codigo_factura=codigo_factura;
        this.sub_total=sub_total;
        this.iva=iva;
        this.total=total;
        this.cantidad_items=cantidad_items;
        
        //establecemos los valores iniciales
        setValoresIniciales();
        //agregamos las rows en base a la cantidad de items agregados
        DefaultTableModel modelPrincipal = (DefaultTableModel) this.Table_productos_ventas.getModel();//modelo de la tabla
        for(int i=0;i<this.cantidad_items;i++){
            
            modelPrincipal.addRow(new Object[]{"", "", ""});
        }
         //llenamos la tabla con el detalle de los productos
         for(int filas=0;filas<this.cantidad_items;filas++){
               //recorremos las columnas
               for(int columnas=0;columnas<5;columnas++){
                   this.Table_productos_ventas.setValueAt(Detalle_tabla_productos[filas][columnas], filas, columnas);
                   
               }
            }
    }

    private D_venta_realizada(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_factura = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_iva = new javax.swing.JLabel();
        lbl_subtotal = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_productos_ventas = new javax.swing.JTable();
        btn_buscar4 = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(36, 36, 36));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡Venta realizada con éxito!");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo de Factutra:");

        lbl_fecha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha.setText("0001");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha:");

        txt_cliente.setEditable(false);
        txt_cliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_cliente.setText("jTextField1");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cliente:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total :");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("IVA:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sub Total:");

        lbl_factura.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_factura.setForeground(new java.awt.Color(255, 255, 255));
        lbl_factura.setText("0001");

        lbl_total.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total.setText("Total :");

        lbl_iva.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_iva.setForeground(new java.awt.Color(255, 255, 255));
        lbl_iva.setText("Total :");

        lbl_subtotal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_subtotal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_subtotal.setText("Total :");

        Table_productos_ventas.setBackground(new java.awt.Color(255, 255, 255));
        Table_productos_ventas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Table_productos_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Sub Total"
            }
        ));
        Table_productos_ventas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Table_productos_ventas.setCellSelectionEnabled(true);
        Table_productos_ventas.setEnabled(false);
        Table_productos_ventas.setFocusable(false);
        Table_productos_ventas.setRowHeight(20);
        Table_productos_ventas.setSelectionBackground(new java.awt.Color(51, 102, 255));
        Table_productos_ventas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Table_productos_ventas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Table_productos_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_productos_ventasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table_productos_ventas);
        Table_productos_ventas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Table_productos_ventas.getColumnModel().getColumnCount() > 0) {
            Table_productos_ventas.getColumnModel().getColumn(0).setPreferredWidth(100);
            Table_productos_ventas.getColumnModel().getColumn(1).setPreferredWidth(350);
            Table_productos_ventas.getColumnModel().getColumn(2).setPreferredWidth(100);
            Table_productos_ventas.getColumnModel().getColumn(3).setPreferredWidth(100);
            Table_productos_ventas.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        btn_buscar4.setBackground(new java.awt.Color(51, 102, 255));
        btn_buscar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga-directa.png"))); // NOI18N
        btn_buscar4.setText("Guardar");
        btn_buscar4.setColorHover(new java.awt.Color(0, 0, 0));
        btn_buscar4.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_buscar4.setFocusable(false);
        btn_buscar4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btn_buscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(lbl_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_subtotal)
                                    .addGap(61, 61, 61)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_iva)
                                    .addGap(78, 78, 78)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_total)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_buscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lbl_fecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lbl_factura))
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbl_subtotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbl_iva)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_total)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_buscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table_productos_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_productos_ventasMouseClicked
        // TODO add your handling code here:
        

            

        
    }//GEN-LAST:event_Table_productos_ventasMouseClicked

    private void btn_buscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void setValoresIniciales(){
        
        try{
            this.txt_cliente.setText(this.cliente);
            this.lbl_fecha.setText(this.fecha);
            this.lbl_factura.setText(this.codigo_factura);
            this.lbl_subtotal.setText(String.valueOf(this.sub_total));
            this.lbl_iva.setText(String.valueOf(this.iva));
            this.lbl_total.setText(String.valueOf(this.total));
        }catch(Exception ex){
            System.out.println(ex);
        }
        
        
       
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_venta_realizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_venta_realizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_venta_realizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_venta_realizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_venta_realizada dialog = new D_venta_realizada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_productos_ventas;
    private rsbuttom.RSButtonMetro btn_buscar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_factura;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_iva;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txt_cliente;
    // End of variables declaration//GEN-END:variables
}
