/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Ctr_configuraciones;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Panel_configuraciones extends javax.swing.JPanel {

    /**
     * Creates new form Panel_configuraciones
     */
    public Panel_configuraciones() {
        initComponents();
        //al cargar el frame validamos si el modulo de ventas esta disponible
        int EstadoModuloVentas=new Ctr_configuraciones().EstadoModuloVentas();
        if(EstadoModuloVentas==1){
            this.Check_modulo_ventas.setSelected(true);
        }else{
            this.Check_modulo_ventas.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Check_modulo_ventas = new javax.swing.JCheckBox();
        btn_lista_productos1 = new rsbuttom.RSButtonMetro();
        btn_lista_productos2 = new rsbuttom.RSButtonMetro();
        btn_lista_productos3 = new rsbuttom.RSButtonMetro();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Check_modulo_ventas.setBackground(new java.awt.Color(51, 102, 255));
        Check_modulo_ventas.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Check_modulo_ventas.setForeground(new java.awt.Color(255, 255, 255));
        Check_modulo_ventas.setSelected(true);
        Check_modulo_ventas.setText("    Modulo de ventas");
        Check_modulo_ventas.setToolTipText("");
        Check_modulo_ventas.setFocusable(false);
        Check_modulo_ventas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Check_modulo_ventas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Check_modulo_ventasItemStateChanged(evt);
            }
        });
        Check_modulo_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_modulo_ventasActionPerformed(evt);
            }
        });

        btn_lista_productos1.setBackground(new java.awt.Color(51, 102, 255));
        btn_lista_productos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btn_lista_productos1.setText("Datos de usuario");
        btn_lista_productos1.setColorHover(new java.awt.Color(36, 36, 36));
        btn_lista_productos1.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_lista_productos1.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_lista_productos1.setFocusPainted(false);
        btn_lista_productos1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_lista_productos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_productos1ActionPerformed(evt);
            }
        });

        btn_lista_productos2.setBackground(new java.awt.Color(51, 102, 255));
        btn_lista_productos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga-directa.png"))); // NOI18N
        btn_lista_productos2.setText("Respaldo de Datos");
        btn_lista_productos2.setColorHover(new java.awt.Color(36, 36, 36));
        btn_lista_productos2.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_lista_productos2.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_lista_productos2.setFocusPainted(false);
        btn_lista_productos2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_lista_productos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_productos2ActionPerformed(evt);
            }
        });

        btn_lista_productos3.setBackground(new java.awt.Color(51, 102, 255));
        btn_lista_productos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir.png"))); // NOI18N
        btn_lista_productos3.setText("Cargar datos Respaldados");
        btn_lista_productos3.setColorHover(new java.awt.Color(36, 36, 36));
        btn_lista_productos3.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_lista_productos3.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_lista_productos3.setFocusPainted(false);
        btn_lista_productos3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_lista_productos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_productos3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_lista_productos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_lista_productos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_lista_productos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Check_modulo_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap(763, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Check_modulo_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_lista_productos1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_lista_productos2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_lista_productos3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void Check_modulo_ventasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Check_modulo_ventasItemStateChanged
           // TODO add your handling code here:
        
        
        if(this.Check_modulo_ventas.isSelected()){
            new Ctr_configuraciones().Activar_Desactivar_Ventas(1);
        }else{
            new Ctr_configuraciones().Activar_Desactivar_Ventas(0);
        }
        
    }//GEN-LAST:event_Check_modulo_ventasItemStateChanged

    private void btn_lista_productos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_productos1ActionPerformed
        // TODO add your handling code here:
        //abrimos el frame donde se eleccionara
        D_editar_datos_usuario du=new D_editar_datos_usuario(new javax.swing.JFrame(),true);
        du.setVisible(true);
    }//GEN-LAST:event_btn_lista_productos1ActionPerformed

    private void btn_lista_productos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_productos2ActionPerformed
        // TODO add your handling code here:
        new D_descargar_datos(new javax.swing.JFrame(),true).setVisible(true);
    }//GEN-LAST:event_btn_lista_productos2ActionPerformed

    private void btn_lista_productos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_productos3ActionPerformed
        // TODO add your handling code here:
        new D_cargar_datos(new javax.swing.JFrame(),true).setVisible(true);
    }//GEN-LAST:event_btn_lista_productos3ActionPerformed

    private void Check_modulo_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_modulo_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Check_modulo_ventasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check_modulo_ventas;
    private rsbuttom.RSButtonMetro btn_lista_productos1;
    private rsbuttom.RSButtonMetro btn_lista_productos2;
    private rsbuttom.RSButtonMetro btn_lista_productos3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
