/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Ctr_configuraciones;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Panel_configuraciones extends javax.swing.JPanel {

    /**
     * Creates new form Panel_configuraciones
     */
    public Panel_configuraciones() {
        initComponents();
        //al cargar el frame validamos si el modulo de ventas esta disponible
        int EstadoModuloVentas=new Ctr_configuraciones().EstadoModuloVentas();
        if(EstadoModuloVentas==1){
            this.Check_modulo_ventas.setSelected(true);
        }else{
            this.Check_modulo_ventas.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Check_modulo_ventas = new javax.swing.JCheckBox();
        Check_modulo_ventas1 = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Check_modulo_ventas.setBackground(new java.awt.Color(255, 255, 255));
        Check_modulo_ventas.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Check_modulo_ventas.setForeground(new java.awt.Color(0, 0, 0));
        Check_modulo_ventas.setSelected(true);
        Check_modulo_ventas.setText("Modulo de ventas");
        Check_modulo_ventas.setFocusable(false);
        Check_modulo_ventas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Check_modulo_ventasItemStateChanged(evt);
            }
        });

        Check_modulo_ventas1.setBackground(new java.awt.Color(255, 255, 255));
        Check_modulo_ventas1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Check_modulo_ventas1.setForeground(new java.awt.Color(0, 0, 0));
        Check_modulo_ventas1.setSelected(true);
        Check_modulo_ventas1.setText("Modulo Actualizar Stock");
        Check_modulo_ventas1.setFocusable(false);
        Check_modulo_ventas1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Check_modulo_ventas1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Check_modulo_ventas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Check_modulo_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(763, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Check_modulo_ventas)
                .addGap(36, 36, 36)
                .addComponent(Check_modulo_ventas1)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void Check_modulo_ventasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Check_modulo_ventasItemStateChanged
           // TODO add your handling code here:
        
        
        if(this.Check_modulo_ventas.isSelected()){
            new Ctr_configuraciones().Activar_Desactivar_Ventas(1);
        }else{
            new Ctr_configuraciones().Activar_Desactivar_Ventas(0);
        }
        
    }//GEN-LAST:event_Check_modulo_ventasItemStateChanged

    private void Check_modulo_ventas1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Check_modulo_ventas1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Check_modulo_ventas1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check_modulo_ventas;
    private javax.swing.JCheckBox Check_modulo_ventas1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
