/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author DELL
 */
public class Panel_ventas extends javax.swing.JPanel {

    /**
     * Creates new form Panel_ventas
     */
    public Panel_ventas() {
        initComponents();
        this.Jtable_ventas.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 18));
        // cambia el fondo del encabezado de la tabla
        this.Jtable_ventas.getTableHeader().setBackground(new Color(36,36,36));
        this.Jtable_ventas.getTableHeader().setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_nueva_venta = new rsbuttom.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_ventas = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_nueva_venta.setBackground(new java.awt.Color(36, 36, 36));
        btn_nueva_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btn_nueva_venta.setText("   Nueva Venta");
        btn_nueva_venta.setColorHover(new java.awt.Color(51, 102, 255));
        btn_nueva_venta.setColorNormal(new java.awt.Color(36, 36, 36));
        btn_nueva_venta.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_nueva_venta.setFocusPainted(false);
        btn_nueva_venta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_nueva_venta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_nueva_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueva_ventaActionPerformed(evt);
            }
        });

        Jtable_ventas.setBackground(new java.awt.Color(255, 255, 255));
        Jtable_ventas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jtable_ventas.setForeground(new java.awt.Color(0, 0, 0));
        Jtable_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Jtable_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jtable_ventas.setFocusCycleRoot(true);
        Jtable_ventas.setGridColor(new java.awt.Color(255, 255, 255));
        Jtable_ventas.setRowHeight(22);
        Jtable_ventas.setSelectionBackground(new java.awt.Color(51, 102, 255));
        Jtable_ventas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Jtable_ventas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Jtable_ventas.setShowVerticalLines(false);
        Jtable_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtable_ventasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable_ventas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_nueva_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_nueva_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nueva_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueva_ventaActionPerformed
        // TODO add your handling code here:
        D_Nueva_Ventas d=new D_Nueva_Ventas(new javax.swing.JFrame(),true);
        d.setVisible(true);
        while(d.isShowing()){
            //no hace nada
        }

    }//GEN-LAST:event_btn_nueva_ventaActionPerformed

    private void Jtable_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtable_ventasMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int select =this.Jtable_ventas.rowAtPoint(evt.getPoint());

            String Codigo_identificador=this.Jtable_ventas.getValueAt(select,0).toString();
            String Marca=this.Jtable_ventas.getValueAt(select,2).toString();
            D_editar_producto d= new D_editar_producto(new javax.swing.JFrame(),true,Codigo_identificador,Marca);
            d.setVisible(true);

            while(d.isShowing()){

            }
            
        }
    }//GEN-LAST:event_Jtable_ventasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtable_ventas;
    private rsbuttom.RSButtonMetro btn_nueva_venta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
