/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DELL
 */
public class Panel_reportes extends javax.swing.JPanel {

    /**
     * Creates new form Panel_reportes
     */
    public Panel_reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_lista_productos = new rsbuttom.RSButtonMetro();
        btn_lista_productos1 = new rsbuttom.RSButtonMetro();
        btn_lista_productos2 = new rsbuttom.RSButtonMetro();
        btn_lista_productos3 = new rsbuttom.RSButtonMetro();
        btn_lista_productos4 = new rsbuttom.RSButtonMetro();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_lista_productos.setBackground(new java.awt.Color(51, 102, 255));
        btn_lista_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresion.png"))); // NOI18N
        btn_lista_productos.setText("Lista de Productos");
        btn_lista_productos.setColorHover(new java.awt.Color(36, 36, 36));
        btn_lista_productos.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_lista_productos.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_lista_productos.setFocusPainted(false);
        btn_lista_productos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_lista_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_productosActionPerformed(evt);
            }
        });

        btn_lista_productos1.setBackground(new java.awt.Color(51, 102, 255));
        btn_lista_productos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresion.png"))); // NOI18N
        btn_lista_productos1.setText("Detalle de un Producto");
        btn_lista_productos1.setColorHover(new java.awt.Color(36, 36, 36));
        btn_lista_productos1.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_lista_productos1.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_lista_productos1.setFocusPainted(false);
        btn_lista_productos1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_lista_productos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_productos1ActionPerformed(evt);
            }
        });

        btn_lista_productos2.setBackground(new java.awt.Color(51, 102, 255));
        btn_lista_productos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresion.png"))); // NOI18N
        btn_lista_productos2.setText("Lista de Marcas");
        btn_lista_productos2.setColorHover(new java.awt.Color(36, 36, 36));
        btn_lista_productos2.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_lista_productos2.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_lista_productos2.setFocusPainted(false);
        btn_lista_productos2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_lista_productos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_productos2ActionPerformed(evt);
            }
        });

        btn_lista_productos3.setBackground(new java.awt.Color(51, 102, 255));
        btn_lista_productos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresion.png"))); // NOI18N
        btn_lista_productos3.setText("Detalle de una Factura");
        btn_lista_productos3.setColorHover(new java.awt.Color(36, 36, 36));
        btn_lista_productos3.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_lista_productos3.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_lista_productos3.setFocusPainted(false);
        btn_lista_productos3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_lista_productos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_productos3ActionPerformed(evt);
            }
        });

        btn_lista_productos4.setBackground(new java.awt.Color(51, 102, 255));
        btn_lista_productos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresion.png"))); // NOI18N
        btn_lista_productos4.setText("Listar Facturas");
        btn_lista_productos4.setColorHover(new java.awt.Color(36, 36, 36));
        btn_lista_productos4.setColorNormal(new java.awt.Color(51, 102, 255));
        btn_lista_productos4.setColorPressed(new java.awt.Color(84, 88, 91));
        btn_lista_productos4.setFocusPainted(false);
        btn_lista_productos4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_lista_productos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_productos4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_lista_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lista_productos3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_lista_productos1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_lista_productos2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_lista_productos4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_lista_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lista_productos2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lista_productos1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_lista_productos3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lista_productos4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(330, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lista_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_productosActionPerformed
        // TODO add your handling code here:
        Generar_reporte_listar_productos();
    }//GEN-LAST:event_btn_lista_productosActionPerformed

    private void btn_lista_productos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_productos1ActionPerformed
        // TODO add your handling code here:
        //abrimos el frame donde se eleccionara
        R_seleccionar_producto_reporte dspr=new R_seleccionar_producto_reporte(new javax.swing.JFrame(),true);
        dspr.setVisible(true);
    }//GEN-LAST:event_btn_lista_productos1ActionPerformed

    private void btn_lista_productos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_productos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lista_productos2ActionPerformed

    private void btn_lista_productos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_productos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lista_productos3ActionPerformed

    private void btn_lista_productos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_productos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lista_productos4ActionPerformed
    private void Generar_reporte_listar_productos() {
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConextion();
            //String path = "src\\Reportes\\R_lista_productos.jasper";
            //hacemos el mapeo de los parametros
            JasperReport reporte =(JasperReport) JRLoader.loadObject(getClass().getResource("\\Reportes\\R_lista_productos.jasper"));
            
            //llenamos el rpeorte
            JasperPrint jprint = JasperFillManager.fillReport(reporte,null,conn);
            
            //creamos la vista del reporte
            JasperViewer view = new JasperViewer(jprint, false);

            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            JOptionPane.showMessageDialog(null, "El reporte ha sido generado con exito");

            view.setVisible(true);
            view.setTitle("IVED Lista de productos");
           // view.setIconImage(new ImageIcon(getClass().getResource("/img/IVED_isotipo.png")).getImage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btn_lista_productos;
    private rsbuttom.RSButtonMetro btn_lista_productos1;
    private rsbuttom.RSButtonMetro btn_lista_productos2;
    private rsbuttom.RSButtonMetro btn_lista_productos3;
    private rsbuttom.RSButtonMetro btn_lista_productos4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
